apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization-service
  template:
    metadata:
      labels:
        app: organization-service
    spec:
      containers:
        - name: organization-service
          image: akash6637.azurecr.io/organization-service:v1.4
          ports:
            - containerPort: 8083
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: azuresql-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: azuresql-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azuresql-secret
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: organization-service
spec:
  selector:
    app: organization-service
  ports:
    - port: 80
      targetPort: 8083
